[tool.black]
line-length = 120

[tool.isort]
profile = "black"
skip_gitignore = true
line_length = 120
known_django = "django"
sections = ["FUTURE","STDLIB","THIRDPARTY","DJANGO","FIRSTPARTY","LOCALFOLDER"]
no_lines_before = "LOCALFOLDER"
from_first = true
force_sort_within_sections = true
combine_as_imports = true
